services:
  # 데이터베이스 서비스 정의
  db:
    image: postgres:15
    container_name: pps-postgres  # 컨테이너 이름 고정
    restart: always
    environment:
      POSTGRES_USER: ${RDB_USER}
      POSTGRES_PASSWORD: ${RDB_PASSWORD}
      POSTGRES_DB: ${RDB_NAME}
    ports:
      - "8003:5432" # " PostgreSQL 포트 5432를 내 컴퓨터에 8003로 포트 포워딩"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 데이터 영구 저장 (컨테이너 삭제돼도 유지됨)
    env_file:
      - .env
# 볼륨 정의 (데이터 저장소)
volumes:
  postgres_data: